---
version: "3"

services:
  app:
    build: .
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      JDBC_URL: jdbc:postgresql://db:5432/pet
      JDBC_USERNAME: pet
      JDBC_PASSWORD: pet
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: pet
      POSTGRES_PASSWORD: pet
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

volumes:
  postgresql:
  postgresql_data:
