# builder
FROM openjdk:20-slim AS builder
WORKDIR /workspace/app

COPY gradle gradle
COPY build.gradle settings.gradle gradlew ./
COPY src src

RUN ./gradle bootJar


# final container
FROM openjdk:20-slim

COPY --from=builder /workspace/app/build/libs/bswe3b.jar /app.jar

EXPOSE 8080/tcp

CMD ["java", "-jar", "/app.jar"]
