---
name: Group

on:
    push:
    pull_request:

jobs:
    check_all:
        name: Checks Group
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-java@v3
              with:
                java-version: '20'
                distribution: 'corretto'
            - run: gradle check

    build_all:
        name: Build Group
        runs-on: ubuntu-latest
        needs: 
            - check_all

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-java@v3
              with:
                java-version: '20'
                distribution: 'corretto'
            - run: gradle build

    hadolint_all:
        name: Lint Dockerfile
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: hadolint/hadolint-action@v3.1.0
              with:
                dockerfile: Dockerfile

# folgendes soll ausgeführt werden:
# checkstyle & pmd checks
  # gradle check - tests, checkstyle, pmd
  # gradle checkstyleMain checkstyleTest pmdMain pmdTest
# hadolint



#4 ADD: Implemented config to run the service registry
# feat(config): implemented config to run the service registry; fix #4
#11 ADD: Get-Request method to retrieve the actual port of the instance
# chore: fixes #11 to add GET to retrieve the actual port


# /**
#  * Returns the server port number.
#  * @return port number
# */
# @GetMapping("/environment")
# public int retrieveEnvironment() { 
#     return environment.getProperty("local.server.port");
# }
