---
name: Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  conform:
    runs-on: ubuntu-latest
    name: Conform

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: siderolabs/conform@v0.1.0-alpha.27
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  test:
    runs-on: ubuntu-latest
    name: Unit Tests
    strategy:
      max-parallel: 4
      matrix:
        java-version: ['20']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: "${{ matrix.java-version }}"
          distribution: "corretto"
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run Tests
        run: ./gradlew test

  check:
    runs-on: ubuntu-latest
    name: Check Code
    strategy:
      max-parallel: 4
      matrix:
        java-version: ['20']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: "${{ matrix.java-version }}"
          distribution: "corretto"
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run Checks
        run: ./gradlew check

  hadolint:
    runs-on: ubuntu-latest
    name: Lint Dockerfile

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

  build:
    runs-on: ubuntu-latest
    name: Build Jar File
    needs:
      - test
      - check
    strategy:
      max-parallel: 4
      matrix:
        java-version: ['20']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: "${{ matrix.java-version }}"
          distribution: "corretto"
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build Jar
        run: ./gradlew bootJar
      
      - uses: actions/upload-artifact@v3
        with:
          name: spring-boot-jar
          path: build/libs/bswe3b.jar

  container:
    runs-on: ubuntu-latest
    name: Container
    needs:
      - build
      - hadolint
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Download Jar
        uses: actions/download-artifact@v3
        with:
          name: spring-boot-jar
          path: build/libs/
    
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: ghcr.io/${{ github.repository }}:latest
          push: ${{ github.ref == 'refs/heads/main' }}
